library(DESeq2)
count <- read.table("http://bi.biopapyrus.net/data/count2g.txt",sep = "\t", header = T, row.names = 1)
count <- as.matrix(count)
group <- data.frame(con = factor(c("A", "A", "A", "B", "B", "B")))
dds <- DESeqDataSetFromMatrix(countData = count, colData = group, design = ~ con)
dds <- DESeq(dds)
res <- results(dds)
head(res)
plotMA(res, alpha = 0.01)

dds <- DESeqDataSetFromMatrix(countData = count, colData = group, design = ~ con)
dds <- estimateSizeFactors(dds)
dds <- estimateDispersions(dds)
dds <- nbinomWaldTest(dds)
res <- results(dds)
head(res)
write.table(res, file = "result.txt", row.names = T, col.names = T, sep = "\t")